
import { ThemeProvider } from "@mui/material"
import theme from "@/theme/theme"


export const metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <head>
      <link 
          rel='preload'
          href='./public/assets/fonts/Vazirmatn-Regular.ttf'
          as='font'
          crossOrigin='anonymous'
                          
      ></link>
      <link 
          rel='preload'
          href='./public/assets/fonts/Vazirmatn-Bold.ttf'
          as='font'
          crossOrigin='anonymous'
      ></link>
      </head>
       <body>{children}</body>
      
    </html>
  )
}
